### ISSUE TITLE
additional patron information

### ISSUE THREAD

**Issue by nichtich** [gbv/paia#29]
Additional patron information is not supported on purpose, nor changing this information. One should first think about what patron information is actually wanted. Additional patron information is more likely to be implemented in a different API but PAIA auth and scopes may be related to this.

A quick survey of possible patron information in addition to name and email:

## membership
A patron account may 

* belong to one or more user groups ([`sioc:UserGroup`](http://rdfs.org/sioc/spec/#term_Usergroup))
* have a start date (in general or for each user group?): 
* make the patron a member of some organization (`org:memberOf`).

Rob Styles suggested the [Participation ontology](http://vocab.org/participation/schema). See <http://www.w3.org/TR/vocab-people/> for pointers to relevant ontologies, includin [SIOC](http://rdfs.org/sioc/spec/) and [Organization Ontology](http://www.w3.org/TR/vocab-org/).

## addresses

use vCard/jCard. This should better be part of another API.

**Comment by JonathanRowell** [comment]
I don't know of any libraries that would even comtemplate a patron changing his address online - although may other services do allow it. So I don't see the need for a vCard.

**Comment by nichtich** [comment]
PAIA 1.0.7 introduces an optional, repeatable `type` field for patron types. It's up to the application how these fields are interpreted (membership, roles, access rights...).
