### ISSUE TITLE
RDF

### ISSUE THREAD

**Issue by JonathanRowell** [gbv/paia#43]
"Information expressed by PAIA core responses in JSON, can be expressed in RDF as well"

I once had a boss who, when I said something like that above, used to say "Jonathan, muss das sein?".

"The address field SHOULD NOT be mapped to RDF properties such as schema:address and vcard:hasAddress"

There was a time when I thought that vCard was a good idea, because you could import them into all sorts of programs.

"The Ontology has not been finalized yet!"

That doesn't surprise me. 

We had an XML option in DAIA, why is this missing in PAIA and what is the real use of RDF ontologies for the man in the street? The data which PAIA is accessing is his data and his data alone.

**Comment by nichtich** [comment]
You are right. I created https://github.com/gbv/paia/issues/21 and will move PAIA ontology to an independent specification.
