### ISSUE TITLE
doc.storageid deprecated?

### ISSUE THREAD

**Issue by lahmann** [gbv/paia#54]
`doc.storageid` is deprecated since PAIA 1.1.0 - sending a request with a defined location for pick-up is an often occurring use case in our house. Is there a reason why `doc.storageid` got deprecated for requests?

**Comment by nichtich** [comment]
This field has ben replaced by [conditions and confirmations](http://gbv.github.io/paia/paia.html#conditions-and-confirmations) in PAIA 1.3.0. Still it may be used for backwards compatibility, being mapped to a confirmation.
